---
page-layout: full
toc: true
---

<!--Please delete or replace with your own clarity-->
{{< include /files/includes/_msclarity.qmd >}}


## Selected publications
1.  W. Zhang,*  *et al. * ***Science*** 2025, DOI: 10.1126/science.adx5285.
2.  W. Zhang,*  *et al. * ***Science*** 2023, 379, 807–811.
3.  W. Zhang,*  *et al. * ***Nat. Commun.*** 2024,15, 5785.
4. W. Zhang, *et al.* ***Angew. Chem. Int. Ed.*** 2024, 63, e202319580.
5. W. Zhang*, *et al.* ***Angew. Chem. Int. Ed.*** 2025, 64,  e202500559.


## Full list of publications 
 ([ORCID: 0000-0003-4506-6583](http://orcid.org/0000-0003-4506-6583) | [Google Scholar](https://scholar.google.com/citations?hl=en&user=ySqn8GcAAAAJ&view_op=list_works&sortby=pubdate))

15: **W. Zhang**,* B. Yang, B. Jackson, J. Zhao, H. Shi, D. Camaioni,  S. Kim, H. Wang, J. Szanyi, M. Lee,* J. G. Chen and J. A. Lercher,*  *Integrating Low-temperature PVC and Polyolefin Upgrading*, ***Science***. 2025, DOI: 10.1126/science.adx5285.[PDF](https://doi.org/10.1126/science.adx5285)

14: **Wei Zhang**,* Sungmin Kim, Michele L. Sarazen, Mingyuan He, Jingguang G. Chen and Johannes A. Lercher,* *Advances and Challenges in Low-temperature Upcycling of Waste Polyolefins via Tandem Catalysis*, ***Angew. Chem. Int. Ed*** . 2025, e202500559. [PDF](https://doi.org/10.1002/anie.202500559)

13: **W. Zhang**,* R. Khare, S. Kim, L. Hale, W. Hu, C. Yuan, Y. Sheng, P. Zhang, L. Wahl, J. Mai, B. Yang, O. Y. Gutiérrez, D. Ray, J. Fulton, D. Camaioni, J. Hu, H. Wang, M. Lee and J. A. Lercher,* *Active species in chloroaluminate ionic liquids catalyzing low-temperature polyolefin deconstruction* , ***Nat. Commun.*** 2024, 15, 5785.(Editor's Highlight paper) [PDF](https://doi.org/10.1038/s41467-024-49827-4)

12: **W. Zhang**, H. Yao, R. Khare, P. Zhang, B.  Yang, W. Hu, D. Ray, J. Hu, D. Camaioni, H. Wang, S. Kim, M. Lee, M. Sarazen, J. G. Chen, J. A. Lercher,* *Hydride transfer as key to catalytic upcycling of polyethylene into liquid alkanes.* ***Angew. Chem. Int. Ed.*** 2024, 63, e202319580. [PDF](https://doi.org/10.1002/anie.202319580)

11: **W. Zhang**,* S. Kim, L. Wahl, R. Khare, L. Hale, J. Hu, D Camaioni, O.Gutiérrez, Y. Liu, J. A. Lercher,* *Low-temperature upcycling of polyolefins into liquid alkanes via tandem cracking-alkylation*. ***Science*** 2023, 379, 807–811.[PDF](https://doi.org/10.1126/science.ade7485)

10: **W. Zhang**, P. Oulego, S. K. Sharma, X. Yang, L-J. Li, G. Rothenberg, N. R. Shiju, *Self-exfoliated Synthesis of Transition Metal Phosphate Nanolayers for Selective Aerobic Oxidation of Ethyl Lactate to Ethyl Pyruvate.* ***ACS Catal.*** 2020, 10, 3958-3967. [PDF](https://pubs.acs.org/doi/10.1021/acscatal.9b04452)
    
9: **W. Zhang**, C. Xu, T. Kobayashi, Z. Guo, M. Pruski, W Huang, *Hydrazone-linked heptazine-based mesoporous conjugated polymer for visible-light-driven oxidation of benzyl alcohols with molecular oxygen.****Chem. Eur. J.*** 2020, 26, 7358-7364. [PDF](https://doi.org/10.1002/chem.202000934)

8: **W. Zhang**, Y. Mei, X. Huang, P. Wu, H. Wu, M. Y. He, Size-controlled growth of silver nanoparticles onto functionalized ordered mesoporous polymers for efficient CO2 upgrading. ***ACS Appl. Mater. Interfaces*** 2019, 11, 47, 44241. [PDF](https://pubs.acs.org/doi/10.1021/acsami.9b14927)

7: **W. Zhang**, Y. Mei, P. Wu, H. Wu, M.Y. He, *Highly tunable periodic imidazole-based mesoporous polymers as cooperative catalysts for efficient carbon dioxide fixation.* ***Catal. Sci. Technol.*** 2019, 9, 1030-1038. [PDF](https://doi.org/10.1039/C8CY02595A)

6: **W. Zhang**, P. Oulego, T. K. Slot, G. Rothenberg, N. R. Shiju, *Selective aerobic oxidation of lactate to pyruvate catalysed by vanadium-nitrogen-doped carbon nanosheets.* ***ChemCatChem*** 2019,11, 3831-3387. [PDF](https://doi.org/10.1002/cctc.201900819)

5: **W. Zhang**, G. Innocenti, P. Oulego, H. Wu, B. Ensing, F. Cavani, G. Rothenberg, N. R. Shiju, *Highly selective oxidation of ethyl lactate to ethyl pyruvate catalysed by mesoporous vanadia–titania.****ACS Catal.*** 2018, 8, 2365-2374. [PDF](https://pubs.acs.org/doi/10.1021/acscatal.7b03843)

4: **W. Zhang**, B. Ensing, G. Rothenberg, N. R. Shiju, *Designing effective solid catalysts for biomass conversion: Aerobic oxidation of ethyl lactate to ethyl pyruvate.* ***Green Chem***. 2018, 20, 1866-1873. [PDF](https://doi.org/10.1039/C8GC00032H)

3: **W. Zhang**, G. Innocenti, M. Ferbinteanu, E. V. Ramos Fernandez, A. Sepulveda-Escribano, H. Wu, F. Cavani, G. Rothenberg, N. R. Shiju, *Understanding the oxidative dehydrogenation of ethyl lactate to ethyl pyruvate over vanadia/titania catalysts.* ***Catal. Sci. Technol.*** 2018, 8, 3737-3747.(Front Cover) [PDF](https://doi.org/10.1039/C7CY02309J) 

2: **W. Zhang**, T. Liu, H. Wu, P. Wu, M. Y. He, Direct synthesis of ordered imidazolyl-functionalized mesoporous polymers for efficient chemical fixation of CO2. ***Chem. Commun.*** 2015, 51, 682-684.[PDF](https://doi.org/10.1039/C4CC08062A)

1: **W. Zhang**, Q. Wang, H. Wu, P. Wu, M. Y. He, *A highly ordered mesoporous polymer supported imidazolium-based ionic liquid: an efficient catalyst for cycloaddition of CO2 with epoxides to produce cyclic carbonates.* ***Green Chem.*** 2014, 16, 4767-4774. [PDF](https://doi.org/10.1039/C4GC01245C)